name: 'Miqa Offline Test Kickoff'
description: 'Kick off offline test runs in Miqa, optionally upload outputs, and update metadata or version overrides. Optionally create GitHub status checks.'

inputs:
  MIQA_API_KEY:
    description: 'Miqa API Key'
    required: true
  MIQA_ENDPOINT:
    description: 'Root URL for Miqa (proxy or app domain)'
    required: true
  TRIGGER_ID:
    description: 'Miqa test trigger ID'
    required: true
  VERSION_NAME:
    description: 'Version name for the run'
    required: true
  OUTPUTS_ALREADY_ON_CLOUD:
    description: 'Set to true if outputs are already in cloud storage'
    required: false
    default: 'false'
  GET_METADATA_KEY:
    description: 'Metadata key to match for fetching latest TCR'
    required: false
    default: ''
  GET_METADATA_VALUE:
    description: 'Metadata value to match for fetching latest TCR'
    required: false
    default: ''
  SET_METADATA:
    description: |
      Metadata key-values to set on the run.
      Use YAML or JSON format:

        status: success
        pipeline: exome
    required: false
    default: ''
  LOCATIONS:
    description: |
      Mapping of sample names to file locations.
      Use YAML format:

        sample1: gs://bucket/sample1.vcf
        sample2: s3://bucket/sample2.vcf
    required: false
  OUTPUT_BUCKET_OVERRIDE:
    description: 'Optional bucket name to apply to all samples if only folders are provided in LOCATIONS'
    required: false
  LOCATIONS_FILE:
    description: |
      Path to a file mapping dataset/sample names to file locations.
      Supported formats:

      • YAML or JSON:
          sample1: gs://bucket/sample1.vcf

      • CSV:
        - With headers:
              dataset,path
              sample1,gs://bucket/sample1.vcf

        - Without headers:
              sample1,gs://bucket/sample1.vcf
    required: false
  INSTALLATION_ID:
    description: 'App Installation ID for the miqa-status-check GitHub App (optional)'
    required: false
  CHECK_NAME:
    description: 'Name to display in checks status'
    required: false
    default: ''
  SHA:
    description: 'Commit SHA (e.g., github.sha)'
    required: false
  REPOSITORY:
    description: 'GitHub repository (e.g., github.repository)'
    required: false
  MIQA_GITHUB_APP:
    description: 'Base URL for Miqa GitHub App'
    required: false
    default: 'https://miqa-github.herokuapp.com'
  STRICT:
    description: 'Fail early if paths or sample names are invalid'
    required: false
    default: 'true'
  DRAG_AND_DROP_MODE:
    description: 'Enable drag-and-drop mode (disables strict mode and skips file upload)'
    required: false
    default: 'false'
  DELAY_BEFORE_RUN_SECONDS:
    description: 'Optional delay before test kickoff (seconds). Helps stagger runs in high-concurrency environments.'
    required: false
    default: '3'

outputs:
  run_id:
    description: 'Miqa run ID'
  run_link:
    description: 'Link to the Miqa test chain run'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      shell: bash
      run: |
        echo "::group::Installing Python dependencies"
        pip install -r "${{ github.action_path }}/requirements.txt" --quiet --disable-pip-version-check --no-input
        echo "::endgroup::"

    - name: Set CHECK_NAME dynamically
      shell: bash
      run: |
        mkdir -p /tmp/miqa
        if [ -z "${{ inputs.CHECK_NAME }}" ]; then
          echo "Triggered Miqa Offline Test: ${{ inputs.TRIGGER_ID }}" > /tmp/miqa/check_name
        else
          echo "${{ inputs.CHECK_NAME }}" > /tmp/miqa/check_name
        fi

    - name: Write LOCATIONS to file
      if: ${{ inputs.LOCATIONS != '' }}
      shell: bash
      run: echo "${{ inputs.LOCATIONS }}" > .locations.yaml

    - name: Fetch commit SHA
      id: fetch_sha
      if: ${{ inputs.INSTALLATION_ID != '' }}
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/{repo}/commits/{sha}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        INPUT_REPO: ${{ inputs.REPOSITORY }}
        INPUT_SHA: ${{ inputs.SHA }}

    - name: Save commit SHA
      if: ${{ inputs.INSTALLATION_ID != '' }}
      id: get_sha
      shell: bash
      run: |
        echo "parent_sha=${{ toJSON(fromJSON(steps.fetch_sha.outputs.data).parents[1].sha) }}" >> "$GITHUB_OUTPUT"

    - if: ${{ inputs.INSTALLATION_ID != '' && github.event_name == 'pull_request' && steps.get_sha.outputs.parent_sha != 'null' }}
      shell: bash
      run: |
        mkdir -p /tmp/miqa
        echo "${{ steps.get_sha.outputs.parent_sha }}" > /tmp/miqa/new_sha

    - if: ${{ inputs.INSTALLATION_ID != '' && (github.event_name != 'pull_request' || steps.get_sha.outputs.parent_sha == 'null') }}
      shell: bash
      run: |
        mkdir -p /tmp/miqa
        echo "${{ inputs.SHA }}" > /tmp/miqa/new_sha

    - name: Read CHECK_NAME from file
      id: read_check_name
      shell: bash
      run: echo "value=$(cat /tmp/miqa/check_name)" >> $GITHUB_OUTPUT

    - name: Read NEW_SHA from file
      id: read_new_sha
      shell: bash
      run: echo "value=$(cat /tmp/miqa/new_sha)" >> $GITHUB_OUTPUT

    - name: Create GitHub Check Run
      if: ${{ inputs.INSTALLATION_ID != '' }}
      id: create_check
      uses: fjogeleit/http-request-action@v1.14.0
      with:
        url: '${{ inputs.MIQA_GITHUB_APP }}/create_check_manual'
        method: 'POST'
        timeout: 30000
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"installation_id":"${{ inputs.INSTALLATION_ID }}","repository_full_name":"${{ inputs.REPOSITORY }}", "head_sha":"${{ steps.read_new_sha.outputs.value }}", "check_name":"${{ steps.read_check_name.outputs.value }}", "gha_version":"1.1.5"}'

    - name: Suggest GitHub App installation if check run fails
      if: ${{ failure() && inputs.INSTALLATION_ID != '' }}
      shell: bash
      run: |
        echo "❌ Failed to create GitHub check run."
        echo "🔍 Most common cause: The Miqa GitHub App is not installed on the repository:"
        echo "    ${{ inputs.REPOSITORY }}"
        echo ""
        echo "💡 To fix: Visit your GitHub App settings and install the app on this repo with 'checks: write' permission."
        echo "🔗 https://github.com/apps/YOUR-MIQA-APP-NAME/installations"

    - name: Set CHECK_RUN_ID
      if: ${{ inputs.INSTALLATION_ID != '' }}
      shell: bash
      run: |
        echo "${{ fromJSON(fromJSON(toJSON(steps.create_check.outputs.response))).id }}" > /tmp/miqa/check_run_id

    - name: Read CHECK_RUN_ID from file
      id: read_check_run_id
      shell: bash
      run: echo "value=$(cat /tmp/miqa/check_run_id)" >> $GITHUB_OUTPUT

    - name: Wait briefly before test kickoff
      if: ${{ inputs.DELAY_BEFORE_RUN_SECONDS != '0' }}
      shell: bash
      run: |
        echo "⏱️ Delaying test kickoff by ${{ inputs.DELAY_BEFORE_RUN_SECONDS }}s to reduce request contention..."
        sleep "${{ inputs.DELAY_BEFORE_RUN_SECONDS }}"

    - name: Run MIQA CLI Script
      id: run_miqa
      shell: bash
      run: |
        ADDITIONAL_QUERY="&repo=${{ inputs.REPOSITORY }}&commit=${{ inputs.SHA }}&event_id=${{ steps.read_check_run_id.outputs.value }}&gha_version=miqa-offline-test-kickoff_v1.3${{ inputs.ADDITIONAL_INSTRUCTIONS }}" 
        python "${{ github.action_path }}/run-miqa.py" \
          --server "${{ inputs.MIQA_ENDPOINT }}" \
          --api-key "${{ inputs.MIQA_API_KEY }}" \
          --trigger-id "${{ inputs.TRIGGER_ID }}" \
          --version-name "${{ inputs.VERSION_NAME }}" \
          ${{ inputs.OUTPUTS_ALREADY_ON_CLOUD == 'true' && '--outputs-already-on-cloud' || '' }} \
          ${{ inputs.GET_METADATA_KEY && format('--get-metadata-key \"{0}\"', inputs.GET_METADATA_KEY) || '' }} \
          ${{ inputs.GET_METADATA_VALUE && format('--get-metadata-value \"{0}\"', inputs.GET_METADATA_VALUE) || '' }} \
          ${{ inputs.SET_METADATA && format('--set-metadata \"{0}\"', inputs.SET_METADATA) || '' }} \
          ${{ inputs.LOCATIONS != '' && '--locations-file .locations.yaml' || '' }} \
          ${{ inputs.LOCATIONS_FILE && format('--locations-file \"{0}\"', inputs.LOCATIONS_FILE) || '' }} \
          ${{ inputs.OUTPUT_BUCKET_OVERRIDE && format('--output-bucket-override \"{0}\"', inputs.OUTPUT_BUCKET_OVERRIDE) || '' }} \
          ${{ inputs.DRAG_AND_DROP_MODE != 'true' && inputs.STRICT != 'false' && '--strict' || '' }} \
          --additional-query-params "$ADDITIONAL_QUERY" \
          --json-output-file .miqa_output.json \
          --app-name gh

        echo "run_id=$(jq -r .run_id < .miqa_output.json)" >> $GITHUB_OUTPUT
        echo "run_link=$(jq -r .link < .miqa_output.json)" >> $GITHUB_OUTPUT

    - name: Show upload instructions if no files provided
      if: ${{ (inputs.LOCATIONS == '' && inputs.LOCATIONS_FILE == '') || inputs.DRAG_AND_DROP_MODE == 'true' }}
      shell: bash
      run: |
        grid_upload_url=$(jq -r '.details.links.grid_upload' .miqa_output.json)

        if [ "$INPUT_DRAG_AND_DROP_MODE" = "true" ]; then
          echo "📦 Drag-and-drop mode is enabled. Please upload your files manually via the Miqa web interface:"
        else
          echo "⚠️ No input files were provided via LOCATIONS or LOCATIONS_FILE."
          echo "📥 You must upload files manually through the Miqa web interface:"
        fi

        echo "🔗 Upload here: $grid_upload_url"

    - name: Suggest retry without strict mode
      if: failure() && inputs.STRICT == 'true'
      shell: bash
      run: |
        echo "❌ Miqa test failed in strict mode."
        echo "👉 You can try re-running with 'STRICT: false' to allow missing sample names or unresolved paths."

    - name: Print Miqa Test Run Summary
      shell: bash
      run: |
        # Final summary
        echo "========================================================"
        echo "✅ Miqa Test Run is ready!"
        echo "🧪 Run ID: ${{ steps.run_miqa.outputs.run_id }}"
        echo "🔗 View results: ${{ steps.run_miqa.outputs.run_link }}"
